### ISSUE TITLE
About comparison with CPS and AEL

### ISSUE THREAD

**Issue by LiheYoung** [Haochen-Wang409/U2PL#30]
Hi, really appreciate your work!

I notice that in comparison with CPS and AEL on the Cityscapes (Table 3), you reproduce these two approaches and report the corresponding results. But the reproduced results are far below their original ones. For example, on the 1/8 protocol, reproduced CPS is ``74.31``, but original CPS is ``77.62``, and reproduced AEL is ``75.55``, but original AEL is ``77.90``.

So why the performance gap is so large? Is it due to different labeled data splits or other reasons? Thanks a lot.

**Comment by Haochen-Wang409** [comment]
Hi, actually, comparision to ```CPS``` and ```AEL``` on Cityscapes are asked by reviewers in the rebuttal stage, which is in a hurry.

To be honest, we tried to re-implement ```CPS``` **by ourselves** since it simpilicity and failed to get expected results.
I am not sure what's going wrong with our implementation...

As for ```AEL```, our implementation is based on its official code. The gap of performances might because different labeled data splits, since ```AEL``` randomly select labeled data during training: https://github.com/hzhupku/SemiSeg-AEL/blob/main/semseg/dataset/cityscapes_semi_cp.py#L29, while our method load labeled data from pre-difined ```.txt```.

**Comment by LiheYoung** [comment]
Got it. Thanks. 

Have you tried to directly run their official codes? Although different splits may cause slightly different final results, original AEL reports are much better than your reported ones across ALL settings on the Cityscapes, which is quite strange...

**Comment by Haochen-Wang409** [comment]
Actually, the branch ```with_AEL``` of this repo was modified by the offical AEL... So we are confused about the results too...

**Comment by JoyHuYY1412** [comment]
> Actually, the branch `with_AEL` of this repo was modified by the offical AEL... So we are confused about the results too...

 Sorry to bother you. So can we cite the results of your reproduced AEL? I am not so sure…

**Comment by Haochen-Wang409** [comment]
We recommend you to reproduce AEL with their official code and report your own reproduced results...

**Comment by JoyHuYY1412** [comment]
> We recommend you to reproduce AEL with their official code and report your own reproduced results...

Thank you for your quick reply! 

As you said you modified the official AEL in your with_AEL branch, could you briefly describe what modifications you applied? Thank you so much!

**Comment by Haochen-Wang409** [comment]
The main differences lie in the way of generating labeled ids.
AEL random samples ids while we modified it into loading labeled ids from a ```.txt``` file.

**Comment by JoyHuYY1412** [comment]
> The main differences lie in the way of generating labeled ids.
> AEL random samples ids while we modified it into loading labeled ids from a `.txt` file.

Got it. Thanks!
