### ISSUE TITLE
About teacher student model

### ISSUE THREAD

**Issue by iris0329** [Haochen-Wang409/U2PL#33]
Hi, thanks for opening source this brilliant work.

For this teacher-student architecture, mentioned, follow the typical self-training framework  ... in the 3.1. Sec.

1) But I still wonder is it ok to only use the student? like, select the positive and negative features from the student output. 
2) In the code, the student and teacher are initialized in the same way, using the ImageNet pre-trained params. but the teacher is updated very slow, so it might not learn the feature well, will the positive teacher features be very different from the student anchor?

Looking forward to your reply.

**Comment by Haochen-Wang409** [comment]
Hi, thanks for your attention!

Mean teacher is a common practice in semi-supervised learning and self-supervised learning (MoCo).
In fact, it is obviously OK to use the predictions of student to be positive and negative keys. But I do not recommand to do this, since the keys should be consistent (please refer to MoCo).
Actually, the performances of teacher are usually better than those of student.
The features of teacher may no be **VERY** different from the student but they will be stable over training, providing a consistent target for the anchor to be optimized.

**Comment by iris0329** [comment]
Thanks for your detailed answer, I read the MoCo as your advice, and noticed it stressed that "a stable and consistent target for the anchor to be optimized" is truly important.
