### ISSUE TITLE
Questions about using cutmix

### ISSUE THREAD

**Issue by honglianghe** [Haochen-Wang409/U2PL#40]
Hi Haochen, this is a great job. I have a problem with this, i.e., in the semi-supervised task, the "apply_aug" used in the config.yaml is "cutmix", but the generate_cutout_mask() is used in the generate_unsup_data(). Is there a special consideration here or a typo?

**Comment by Haochen-Wang409** [comment]
Actually, ```cutout``` and ```cutmix``` are very similar and could share the mask, see [here](https://github.com/Haochen-Wang409/U2PL/blob/main/u2pl/dataset/augmentation.py#L520-L534) for details for ```cutmix```.

Specifically, ```cutout``` fills the mask with random variables but ```cutmix``` fill the mask by pasting another image from the same batch.

**Comment by Haochen-Wang409** [comment]
Hi, it might be a misunderstanding.
Our performance (w/ CutMix) **has been adopted CutMix** rather than CutOut.
The implementation of CutMix we simply follow [ReCo](https://github.com/lorenmt/reco).

From the [code](https://github.com/Haochen-Wang409/U2PL/blob/main/u2pl/dataset/augmentation.py#L520-L534), we can tell that ```if mode == "cutmix"```, then ```new_data``` is the mix version of ```data[i]``` and ```data[(i + 1) % batch_size]``` following ```mix_mask```.

For simplicity, CutOut and CutMix can share ```mix_mask``` but with different elements to fill the mask.
For CutOut, we simply make it to 255 (see [here](https://github.com/Haochen-Wang409/U2PL/blob/main/u2pl/dataset/augmentation.py#L508)).
But for CutMix, we mix two images from the same batch (see [here]((https://github.com/Haochen-Wang409/U2PL/blob/main/u2pl/dataset/augmentation.py#L520-L534))).

Please refer to the code for more details.

**Comment by honglianghe** [comment]
@Haochen-Wang409  Thank you very much for your detailed reply. 
But I still have some doubts.
In the case where I did not change the config.yaml (apply_aug: cutmix), but I visualized the images corresponding to image_u_aug and label_u_aug, I found that cutout was used instead of cutmix. What other parameters need to be set here to use cutmix?

**Comment by honglianghe** [comment]
![fusion_3_1652845](https://user-images.githubusercontent.com/89174761/168953665-6e7403c5-58d1-4529-a4f0-11f8b20b10e8.png)
@Haochen-Wang409  As shown in this figure. From left to right: image_u_aug, label_u_aug, low_mask_all, high_mask_all.
It can be seen from the figure that cutout is used, which corresponds to lines 515-516 in u2pl/dataset/augmentation.py.
which is
if mode == "cutmix": mix_mask = generate_cutout_mask([im_h, im_w]).to(device)

**Comment by Haochen-Wang409** [comment]
The ```image_u_aug``` seems right. It is the mixed version of two different images.

**Comment by honglianghe** [comment]
Yes, this solved my doubts. thank you very much.

**Comment by Haochen-Wang409** [comment]
> ![fusion_3_1652845](https://user-images.githubusercontent.com/89174761/168953665-6e7403c5-58d1-4529-a4f0-11f8b20b10e8.png) @Haochen-Wang409 As shown in this figure. From left to right: image_u_aug, label_u_aug, low_mask_all, high_mask_all. It can be seen from the figure that cutout is used, which corresponds to lines 515-516 in u2pl/dataset/augmentation.py. which is if mode == "cutmix": mix_mask = generate_cutout_mask([im_h, im_w]).to(device)

```label_u_aug``` seems a little bit strange, I recommend you to apply a colormap for a better visualization.

Cheers
