### ISSUE TITLE
model_teacher.train() in train_semi.py L361

### ISSUE THREAD

**Issue by EricKani** [Haochen-Wang409/U2PL#64]
The parameters of teacher model is updated by the student model's parameters via EMA. What is the meanings of code of line 361 in train_semi.py? e.g., model_teacher.train(), which enable the statistic info of BN layer in model_teacher to be updated during training, but it also will be overwritten when implement EMA.

https://github.com/Haochen-Wang409/U2PL/blob/8bcf3c672794d84d993ae6a6d4d5e801ce1dc677/train_semi.py#L361

Thanks~
Eric

**Comment by Haochen-Wang409** [comment]
Yes, we let the parameters of BN of the teacher model to update using ```train()``` mode.
This is because we find that if we switch to ```model_teacher.eval()``` in ```train_sup.py``` and evaluate the teacher model's performance, its mIoU is quite low and we have no idea about the reasons... :(
Therefore, we let the BN update during semi-supervised training.

**Comment by EricKani** [comment]
I got it. When you update the teacher model's parameters via EMA (model.parameters), you only transfer the learnable parameters. not running mean and running variance.
So model teacher should use model.train() to update mean and variance by itself.
