### ISSUE TITLE
Results about different splits

### ISSUE THREAD

**Issue by JoyHuYY1412** [Haochen-Wang409/U2PL#69]
Thanks for your advice, I will provide all splits of CPS as an alternative for followers.

_Originally posted by @Haochen-Wang409 in https://github.com/Haochen-Wang409/U2PL/issues/3#issuecomment-1068714107_

**Comment by JoyHuYY1412** [comment]
Hello, thank you for your great job!
I checked your splits for PASCAL VOC dataset, I am not sure what the split for _blender and classic_ setting is separately? And how do you generate the split? I want to follow your work but I think maybe I will run several random splits.

**Comment by Haochen-Wang409** [comment]
Splits provided by: [CPS](https://github.com/charlesCXK/TorchSemiSeg/tree/main/DATA/pascal_voc/subset_train_aug) or [ST++](https://github.com/LiheYoung/ST-PlusPlus/tree/master/dataset/splits/pascal).

In fact, for VOC dataset, it is not necessary to run experiments on the exact same splits. However, for the Cityscapes dataset, since it suffers from a long-tailed label distribution, it is better to run with the same split.

Moreover, I believe you will get similar performances even if with different splits.
